### ISSUE TITLE
Can't resolve 'flex-plugin' 

### ISSUE THREAD

**Issue by grobira** [twilio-professional-services/plugin-autoComplete-wrapup#1]
I've tried to install this repo locally, but I was having an issue regarding the import of `'flex-plugin'` module. 

> Error 1:
> Module not found: Error: Can't resolve 'flex-plugin' in '/Users/giovanni.robira/Projects/plugin-autoComplete-wrapup/src'

I've noticed that this plugins uses version 5.0.4, so I upgraded my Plugin CLI to this version. I'm not sure if I'd an issue when upgrading. 

Also, the reference for the module `'flex-plugins'` might have changed on this release, now it is referred as `"@twilio/flex-plugin"` .

So I've had to change those import : 

> src/AutoCompleteWrapupPlugin.js
```javascript
import { FlexPlugin } from 'flex-plugin';
```

> src/index.js
```javascript
import * as FlexPlugin from 'flex-plugin';
```

To: 

```javascript
import { FlexPlugin } from '@twilio/flex-plugin';
```

```javascript
import * as FlexPlugin from '@twilio/flex-plugin';
```

**Comment by cherylmj01** [comment]
I upgraded the plugin to use the latest version and I tested it by cloning into a new folder and it's working without any issues now.
